name: Concatenate V2Ray Configs

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  concat_and_commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Step 2: Checkout the foreign repository
      - name: Checkout foreign repo
        uses: actions/checkout@v4
        with:
          repository: V2RAYCONFIGSPOOL/V2RAY_SUB
          path: foreign-repo
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: false
          fetch-depth: 1

      # Step 3: Run concatenation script
      - name: Run concatenation script
        run: bash ./script.sh --manager --countries -n 5

      # Step 4: Commit and push to your repo
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update concatenated V2Ray configs" || echo "No changes to commit"
          git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/dorrin-sot/V2RAY_CONFIGS_POOL-Processor.git
          git push origin main
